### ISSUE TITLE
Latest doesn't work

### ISSUE THREAD

**Issue by xNinjaRose** [epinter/tqrespec#13]
![errortqrespec](https://user-images.githubusercontent.com/48578082/61267913-c039e300-a767-11e9-8749-6a6149a2a3ef.PNG)

I pick my character and it says this, and its ridiculous, I have plenty of memory on my PC, 8gb and i highly doubt a simple java program uses even 1gb if anything, so theres some leak going on that should be fixed

**Comment by epinter** [comment]
Must be some bug in the parsing process. Can you send me your player.chr ? This but is not triggered with none of the characters I tested with.

**Comment by xNinjaRose** [comment]
https://www.dropbox.com/s/7gkb4qmk498ugc3/Player.chr?dl=0

and 400mb seems around right for a java type app, making it weirder its running out of memory on a 8gb pc

**Comment by epinter** [comment]
Fixed by 9dde3f09c09d3a1b779cad77834919470e424332 and  5a33b8642815c2f8f467c62f211ede3daef1ff22

**Comment by epinter** [comment]
You can use this test build while I prepare the next release:

https://mega.nz/#!cM9UGajL!qCZqMVRVnfY31d4XcRBxdc-GkOJSLoqay-MHr65pznA

**Comment by xNinjaRose** [comment]
that test build works, i can reset my attrib and mastery back so the fix works, Thanks!
