### ISSUE TITLE
Add Portal enabler in future build

### ISSUE THREAD

**Issue by xNinjaRose** [epinter/tqrespec#16]
I would want to be able to select portals (or a more simpler option id assume, make it so next time you spawn in the save, you're in helos by the rebirth fountain, this would help make Accomplished heroes more usable for a lot who want to lvl up to 40 but feel undergeared so now u have that option to rush thru normal, how it shouldve been when devs implemented it.

**Comment by epinter** [comment]
The game already have a portal to Helos at Corinth.
