### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by CyberNinja04** [epinter/tqrespec#2]
Doesnt even open, says its not made for my OS, how about make it operable on any OS people use and not just 10, make an update for win 7

**Comment by epinter** [comment]
Did you download the tqrespec_withjre.zip ?

**Comment by CyberNinja04** [comment]
i did that, the with jre.zip but it still says the same error about my OS

**Comment by epinter** [comment]
Your windows 7 is 32-bit or 64-bit ?  Please post a screenshot of the error message,
Thanks.

**Comment by epinter** [comment]
Tested. It's working with Windows 7 x64.

**Comment by CyberNinja04** [comment]
![tqrespec-error](https://user-images.githubusercontent.com/52311161/60650330-f6936c00-9e11-11e9-8f3b-9afec7e208f3.PNG)
 Thats the error and its 32-bit, i tried running it on my Win 10 laptop that is not a gaming pc thus i dont play games on it and it works but i try to copy saves from one pc to the other pc and it cant find it, it should work on any version of win 7 regardless anyway, this should be usuable for everyone

**Comment by epinter** [comment]
Well, it's not so easy...

This software is developed in Java language, using JavaFX (standard java framework for graphical user interface). The current version uses Java 9.0, next version will use 11.0.

Oracle is the current owner of Java official implementation, and they dropped 32-bit completely starting from 9.0. And starting from Java 11.0, they separated the JavaFX support from the Java Runtime (JRE/JDK that we download and install), so JavaFX sdk is not included in OpenJDK package anymore.

While there are some open source projects that provides OpenJDK 32-bit (like AdoptOpenJDK, the best of them for developers and end-users), they dont include JavaFX (now called OpenJFX). I still have to search, but at this moment I don't know any project that provides JavaFX binaries for 32-bit, the company the is developing OpenJFX (Gluon) follows Oracle and only releases 64-bit binaries.

I have personal interest in providing a 32-bit version of TQRespec, but not for so long, maybe one version or two is sufficient. Great players of software and hardware industry are abandoning the 32-bit architecture, and users are using it less and less over time. You can see by the steam statistics:

![image](https://user-images.githubusercontent.com/1561280/60680665-911b9b80-9e62-11e9-8132-98ee5ce1ed83.png)

As you can see, only 1% of steam users are have Windows 7 32-bit. I can see a reason for use Windows 7 x64 over Windows 10, but I dont see a reason to keep Windows 7 32-bit (the problems will only increase over time).

Anyway, if I find a sdk to build a 32-bit version I will do it, but I will not consider this a bug. This software requires 64-bit Windows, and will be documented.

Thanks.

**Comment by CyberNinja04** [comment]
Could you implement/help Etienne implement the Mastery Respec into TQ Vault then? i know stat respec is in TQ Vault and i can run the vault fine so thatd prob be the simpler solution, plus having everything all in one app, Vault, stat respec, mastery respec , more ppl would prefer id assume

**Comment by epinter** [comment]
> Could you implement/help Etienne implement the Mastery Respec into TQ Vault then? i know stat respec is in TQ Vault and i can run the vault fine so thatd prob be the simpler solution, plus having everything all in one app, Vault, stat respec, mastery respec , more ppl would prefer id assume

I don't agree, I'm against what is happening with TQVault, it should stay as a vault and not a tool for cheat,respec,etc.. The respec features was merged in tqvault and if you look the interface, the software has no place for that kind of feature. TQVault was very well maintained with vault features, but I have doubt if the quality will be the same with all that features being added. I don't have complete knowledge over the TQVault code, so I can't add a feature like skills respec without add more problems and bugs (I don't like C# so much).

**Comment by epinter** [comment]
I'm currently testing a new build, and with upgraded runtime and libraries I'm able to build a 32bit version. A download link is available at https://github.com/epinter/tqrespec/issues/20.
