### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Shard32** [epinter/tqrespec#20]
hello can you make a 32 bit version for windows becouse i have 32 bit pc system i would upgrade to 64 bit but idk how to and i dont want to risk losing all my files so i really found this program usefull but now im sad that i cant use it ;-;

**Comment by epinter** [comment]
I'm currently testing a new build, and with the upgraded libraries I'm able to build a 32bit version, here the download link: https://1drv.ms/u/s!Al6bs7S_f0Jth3EwKZROlfoawIaI?e=zdpg6L

**Comment by epinter** [comment]
See https://github.com/epinter/tqrespec/releases
