### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by chefranov** [epinter/tqrespec#22]
Hi! I can translate your app into Russian language. How can I do it?

**Comment by epinter** [comment]
Hi, I Like this question!

I already have some preparation for multi language, but it's not activated. You can look the format of the file here:

https://github.com/epinter/tqrespec/blob/master/src/main/resources/i18n/UI.properties

I will enable the multi language support and report to you here (need to implement some logic to get language from game).

Thank you !!

**Comment by chefranov** [comment]
Here is Russian translate
```
#
# Copyright (C) 2019 Emerson Pinter - All Rights Reserved
# Russian translate: Evgeniy Chefranov (titanquest.org.ua)
#

main.strength=Сила
main.intelligence=Интеллект
main.dexterity=Ловкость
main.health=Жизнь
main.energy=Энергия
main.savechar=Сохранить персонажа
main.copychar=Копировать в
main.copycharname=Новое сохранение
main.available=Доступные очки
main.labelselectchar=Выберите вашего персонажа
main.experience=Опыт
main.charlevel=Уровень персонажа
main.gold=Золото
main.savingcharacter=Сохранение...
main.backupcharacter=Создание резервной копии...
main.charclass=Класс
main.difficulty=Сложность
main.attributesTab=Атрибуты
main.skillsTab=Навыки
main.gameNotDetected=Игра не обнаружена
main.chooseGameDirectory=Пожалуйста, выберите папку, где установлена игра
about.title=О программе {0}
about.version=Версия {0}
about.text=Права пренадлежат 2018 Эмерсон Пинтер\nЭто программное обеспечение предоставляется как есть, нет никаких гарантий на него или на доступную или измененную информацию. Всегда делайте резервную копию перед использованием. Это программное обеспечение использует библиотеки с открытым исходным кодом, авторское право на стороннее программное обеспечение принадлежит их соответствующим владельцам.
about.newversion=Доступна новая версия, кликните здесь
alert.saveinprogress_header=Выполняется файловая операция.
alert.saveinprogress_content=Выполняется файловая операция, пожалуйста подождите...
alert.savedbackedup_header=Сохранено
alert.savedbackedup_content=Персонаж сохранён и создана его резервная копия. Откройте папку \"{0}\" для просмотра резервной копии.
alert.errorloadingchar_header=Ошибка загрузки персонажа
alert.errorloadingchar_content=Ошибка чтения атрибутов (health={0},energy={1},str={2},int={3},dex={4}). Это может быть по причине бага, поврежденного файла персонажа или несовместимости версии игры.
alert.errorbackup_header=Ошибка создания резервной копии
alert.errorbackup_content=Произошла ошибка во время создания резервной копии текущего персонажа в папку \"{0}\". Проверьте доступы к папке. Ваш персонаж не был изменён.
alert.errorsaving_header=Ошибка сохранения персонажа
alert.errorsaving_content=Произошла ошибка во время сохранения персонажа.
alert.errorcopying_header=Ошибка копирования персонажа
alert.errorcopying_content=Произошла ошибка во время копирования текущего персонажа в папку \"{0}\". Проверьте доступы к папке. Ваш персонаж не был изменён.
difficulty.0=Норма
difficulty.1=Эпос
difficulty.2=Легенда
skills.availableSkillPoints=Персонаж имеет {0} доступных очков навыков
skills.removeSkillsBefore=Вам необходимо восстановить очки навыка перед манипуляцией с мастерством.
skills.reclaimSkillPoints=Востановить очки навыка
skills.reclaimMasteryPoints=Восстановить {0} очков
skills.removeMastery=Убрать
skills.masteryButton=Мастерство
alert.errorgamerunning_header=Закройте игру для использования TQRespec
alert.errorgamerunning_content=Игра запущена, сохранение и копирование недоступно.
alert.changesinvaliddata=Некорректные данные \"{0}\"
```
And don't forget about window titles & buttons. Usually Cyrillic words are long. And also check Cyrillic font support (in app, mysteries, skills and name of character).

In About window you can add information about a translator (name & site).

**Comment by epinter** [comment]
Thanks !

During the implementation I tested with other languages, and I found better to reduce 3 strings. I didn't found nothing better "Remove Skills".




diff --git a/src/main/resources/i18n/UI.properties b/src/main/resources/i18n/UI.properties
index f536bf0..abd156f 100644
--- a/src/main/resources/i18n/UI.properties
+++ b/src/main/resources/i18n/UI.properties
@@ -7,13 +7,13 @@ main.intelligence=Intelligence
 main.dexterity=Dexterity
 main.health=Health
 main.energy=Energy
-main.savechar=Save Character
+main.savechar=Save
 main.copychar=Copy To
 main.copycharname=New save
 main.available=Available Points
 main.labelselectchar=Select your Character
 main.experience=Experience
-main.charlevel=Character Level
+main.charlevel=Level
 main.gold=Gold
 main.savingcharacter=Saving...
 main.backupcharacter=Backing up...
@@ -44,7 +44,7 @@ difficulty.1=Epic
 difficulty.2=Legendary
 skills.availableSkillPoints=The character have {0} skill points available
 skills.removeSkillsBefore=You need to reclaim the skill points before mastery.
-skills.reclaimSkillPoints=Reclaim Skills Points
+skills.reclaimSkillPoints=Remove Skills
 skills.reclaimMasteryPoints=Reclaim {0} Points
 skills.removeMastery=Remove
 skills.masteryButton=Mastery





![image](https://user-images.githubusercontent.com/1561280/90636510-185fd600-e201-11ea-83ef-bc3dbf8f530b.png)

**Comment by chefranov** [comment]
According your screen we can change translate to short version:
`main.charlevel=Уровень персонажа` to `main.charlevel=Уровень`
`main.savechar=Сохранить персонажа` to `main.savechar=Сохранить`
`main.copychar=Копировать в` to `main.copychar=Копия`

Or maybe we can use font more smaller

And here is my mistake:
`skills.reclaimSkillPoints=Востановить очки навыка` to `skills.reclaimSkillPoints=Восстановить очки навыка`

**Comment by chefranov** [comment]
And try to check character with russian name
[_Эльфийская тян.zip](https://github.com/epinter/tqrespec/files/5098268/_.zip)

**Comment by epinter** [comment]
How to translate "Remove Skills" ?  Убрать навыкаи ?

**Comment by epinter** [comment]
Test build with Russian translation:

The game must be configured to Russian language.

https://1drv.ms/u/s!AqbcmbBetf3hemOmrSYGBw9XNVE?e=SZs1Da

**Comment by chefranov** [comment]
> How to translate "Remove Skills" ? Убрать навыкаи ?
Here is my mistake. Should be
`Убрать навыкаи` -> `Убрать навыки` or `Очистить навыки`

**Comment by chefranov** [comment]
Before I incorrect understood `Copy to`. Correct will be:
```
main.copychar=Копия как
main.copycharname=Имя персонажа
```

**Comment by epinter** [comment]
I prefer to keep the word "New" in the field, so the user don't get confused between the current character name and the destination...  "Новый персонаж" is a correct translation for "New character" ?

**Comment by chefranov** [comment]
> "Новый персонаж" is a correct translation for "New character" ?

Yes

**Comment by epinter** [comment]
![image](https://user-images.githubusercontent.com/1561280/90679394-7955d100-e236-11ea-8067-c6b407372de5.png)
![image](https://user-images.githubusercontent.com/1561280/90679419-8672c000-e236-11ea-8762-4b9ba099ce49.png)

**Comment by chefranov** [comment]
Looks good 👍

**Comment by epinter** [comment]
Added to [v0.8.1](https://github.com/epinter/tqrespec/releases/tag/v0.8.1)
