### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Pyr0x1** [epinter/tqrespec#26]
Hi, could an italian translation be usefeul? Let me know and I can start working on it.

**Comment by epinter** [comment]
Hi. Yes, an italian translation is welcome. 

Look the UI.properties for the strings that needs to be translated : https://github.com/epinter/tqrespec/tree/master/src/main/resources/i18n

Thank you!

**Comment by epinter** [comment]
Included in release v0.8.2.
