### ISSUE TITLE
Add option to change character gender

### ISSUE THREAD

**Issue by xNinjaRose** [epinter/tqrespec#27]
Would be cool to have a feature in TQ Respec to change the gender of the character in the save, so if its a Male character, change to female or vice versa. Would help when sharing saves and changing gender to fit your playstyle while still being able to share saves

**Comment by epinter** [comment]
I will look into it and implement if possible.

**Comment by epinter** [comment]
Released [v0.9.0](https://github.com/epinter/tqrespec/releases/tag/v0.9.0)
