### ISSUE TITLE
Where can I get :tqdatabase project ?

### ISSUE THREAD

**Issue by mimic2300** [epinter/tqrespec#39]
https://github.com/epinter/tqrespec/blob/b2aac16168000dfcf752efa397d0e442a766afaf/settings.gradle#L6

Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching configuration of project :tqdatabase was found. The consumer was configured to find a runtime of a library compatible with Java 17, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally but: ...

Used Java 17 for project and gradle.

**Comment by epinter** [comment]
TQDatabase is private yet. I need to review the code before published. I'm expecting to do it in the next few weeks...

**Comment by mimic2300** [comment]
Weeks? Okay... I'd like to somehow add the option that was in Defiler - resetting mastery and keeping learned skills :)
Or if you know how to do it, it would be a great feature.

**Comment by epinter** [comment]
The project was public until the last update, but I needed to fix some things and remove old git branches, so I made it private to work on it. But my time is short now.

It's an interesting option. But out of the scope for TQRespec, I try to avoid options that give things free to the player (points, skills,etc). Maybe I could add another UI only for "cheats".

Anyway, the TQDatabase project is used to read the database.arz and resource files from game. If you don't want to change how tqrespec reads information from game database, and if you already know gradle, you can use the tqdatabase.jar from the release, put in some directory and configure gradle to read libraries from that dir, and replace all dependencies related to the project.

**Comment by mimic2300** [comment]
I know it's out of scope. I know what I want is a cheat, but if there is already an option to reset the mastery, there could be this option as well.

Feel free to do a checkbox or category with cheat options and use it just the one you want. In addition, it would raise the popularity of the application itself. Because Defiler did this, but it is no longer updated for the current game version and is probably dead. And resetting mastery and keeping skills was unique and only Defiler could do it.

In addition, people will still find a way to do it. So why throw sticks at their feet and take the opportunity. Increase the popularity of the application.

For example, what your application can do is in TQVault. By adding "cheats" options and this one with the skills I suggest you should have a unique app and maybe the only one that can. Which is another reason why people would start using it.

Try to consider it :)

**Comment by epinter** [comment]
TQDatabase repository is now public. The project is stable, but I will refactor part of the code soon.
