### ISSUE TITLE
Child process exited with code 2

### ISSUE THREAD

**Issue by Orannaro** [epinter/tqrespec#47]
**Describe the bug**
When launching TQRespec.exe, I get the error message "Child process exited with code 2". Application does not launch.

***TQRespec version (please complete the following information):***
-0.12

***Operating System (please complete the following information):***
- Windows 11

***Game version (please complete the following information):***
- Titan Quest Anniversary 2.10.21415
![Screenshot 2022-12-11 211756](https://user-images.githubusercontent.com/120335121/206924361-3fbe1c19-5849-4db3-8cbf-e5a26f16bb12.png)

***DLCs installed (please complete the following information):***
-Ragnarok
-Atlantis
-Eternal Embers

***Additional context***
I believe TQ Respec was last updated for the previous TQ version.

**Comment by epinter** [comment]
To know the error that is preventing the application from start we should look at the log. Can you get tqrespec.log from the temporary directory ? You can find the file typing %TEMP% in location bar in Windows Explorer. The file is generated by the application during startup.

Also, please be sure you have most recent [Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).

If the tqrespec.log doesn't have any error message, something is preventing the native launcher to work, a missing dll (from Visual C++ for example), or maybe an antivirus or another security related tool. This kind of failure can be found in **Application** messages with **Windows Event Viewer**.

**Comment by epinter** [comment]
The release 0.12.1 I uploaded a few minutes ago has an update to Java (17.0.5) that can solve minor issues with the native launcher (related to the generic error message).

**Comment by Orannaro** [comment]
Hi!
Thanks for the update.

I copied the files from v0.12 to my game’s main folder and it worked
perfectly then.

Regards,
