### ISSUE TITLE
Run on Steam Deck?

### ISSUE THREAD

**Issue by electrovir** [epinter/tqrespec#49]
Would you be able to make a Steam Deck compatible version? Or provide tips on how to run it on the Steam Deck? (Arch Linux based) It looks like this is written in Java, so could I manually run a `.jar` file maybe?

**Comment by epinter** [comment]
I use Linux to develop and test, so should be possible to build a version to run on Steam. The way it is now, it would ask you to select the game path, and the SaveData would be searched in the current directory. I can put some code to detect Steam Deck, but I don't have one so the final result won't be as I wish, but I think it can work.

Do you know the full path where Steam Deck installs the game and the full path of Player.chr ?

This weekend I will build a version for Linux and post here for you.

**Comment by epinter** [comment]
Here is the build for Linux. Use TQRespec.sh to run, or run ./bin/TQRespec inside TQRespec directory.
https://1drv.ms/u/s!AqbcmbBetf3hgh-5ytT10LqaSPCu?e=X5ZvBg


Copy the database and text to gamedata/ directory, see [Running without the game installed](https://github.com/epinter/tqrespec#running-without-the-game-installed).

Copy your savegames to savedata/ directory, see [Android support](https://github.com/epinter/tqrespec#android-support).

At least for now, you can use this way.

**Comment by electrovir** [comment]
Sweet, thanks! I'll give it a shot!

**Comment by ajgringo619** [comment]
Just tested (on PC, not Steam Deck). Thank you so much! Any chance of getting the latest version?

**Comment by epinter** [comment]
I will take a look at this, issue https://github.com/epinter/tqrespec/issues/55
