### ISSUE TITLE
TQRespec starts but freeze soon after

### ISSUE THREAD

**Issue by Redstorm86** [epinter/tqrespec#50]
I've downloaded the latest version of TQRespec, but when I try to run it nothing happens. I'm on Windows 11 and  I have  the TQ:AE from GOG Anniversary Edition, with Ragnarok and Atlantis DLCs. After I launch TQRespec, when I look in Task Manager, it is listed as a running process and I can End Task it. So, for some reason it is starting but maybe just freezing or something - it never shows any kind of a screen.  I also installed the Microsoft Visual C++ Redist 2015-2022 package as well and it seemed to have no effect. Really at a dead-end here. What can i do?

**Comment by epinter** [comment]
Look at %TEMP%\tqrespec.log, there you can find some error message, like an error opening some file...
I recommend you to look at Antivirus, and specially Anti-ransomware (like the controlled folder access from Windows, try to disable it,).

**Comment by Redstorm86** [comment]
Thank you for your support! :)
I send you a copy of the log file after my last try to opening TqRespec:
[tqrespec log.txt](https://github.com/epinter/tqrespec/files/13282944/tqrespec.log.txt)

I also checked my antivirus ( i use only windows defender) and it didn't block the program at launch

**Comment by epinter** [comment]
You're welcome :)

Weird error... Looks like some native code (related to font/graphics initalization) is failing, this could be a java runtime bug... Can you try with the version 0.12.0 ?

Today I really don't have time to build with a newer java version. But tomorrow I can post here a build for you to test.

`GRAVE: java.lang.UnsatisfiedLinkError: 'boolean com.sun.javafx.font.directwrite.OS.CoInitializeEx(int)'
GRAVE:  at javafx.graphics/com.sun.javafx.font.directwrite.OS.CoInitializeEx(Native Method)
GRAVE:  at javafx.graphics/com.sun.javafx.font.directwrite.DWFactory.getWICFactory(DWFactory.java:127)
GRAVE:  at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.createBitmap(DWGlyph.java:287)
GRAVE:  at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.getCachedBitmap(DWGlyph.java:274)
GRAVE:  at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.getD2DMask(DWGlyph.java:168)
GRAVE:  at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.getPixelData(DWGlyph.java:353)
GRAVE:  at javafx.graphics/com.sun.prism.impl.GlyphCache.getCachedGlyph(GlyphCache.java:259)
GRAVE:  at javafx.graphics/com.sun.prism.impl.GlyphCache.render(GlyphCache.java:149)
GRAVE:  at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.drawString(BaseShaderGraphics.java:2102)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGText.renderText(NGText.java:312)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGText.renderContent2D(NGText.java:270)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NodeEffectInput.getImageDataForBoundedNode(NodeEffectInput.java:237)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NodeEffectInput.filter(NodeEffectInput.java:131)
GRAVE:  at javafx.graphics/com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:185)
GRAVE:  at javafx.graphics/com.sun.scenario.effect.Offset.filter(Offset.java:160)
GRAVE:  at javafx.graphics/com.sun.scenario.effect.Merge.filter(Merge.java:148)
GRAVE:  at javafx.graphics/com.sun.scenario.effect.DelegateEffect.filter(DelegateEffect.java:70)
GRAVE:  at javafx.graphics/com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2384)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGText.renderEffect(NGText.java:221)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2069)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
GRAVE:  at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
GRAVE:  at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
GRAVE:  at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:329)
GRAVE:  at javafx.graphics/com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:143)
GRAVE:  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
GRAVE:  at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
GRAVE:  at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
GRAVE:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
GRAVE:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
GRAVE:  at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
GRAVE:  at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Redstorm86** [comment]
I tried with the 0.12.0 and it's near the same result. But i tried to click on the center of my desktop and the list of my characters in TQ appeared, so i think you are right when you say that it's graphycs initialization failure. I share you the screenshoot:

![Screenshot 2023-11-07 181159](https://github.com/epinter/tqrespec/assets/150154367/03962f73-dfbd-4f8e-839f-a9912bd36ab3)

**Comment by epinter** [comment]
Sorry the delay, please download this build: https://github.com/epinter/tqrespec/releases/tag/dev-20231110

**Comment by Redstorm86** [comment]
I tried the test version but i have the same issue as in previous verions: the app seems to run but the graphic isn't loaded and if i click in the middle of my desktop the information tab and some drop down menu appears and i can scroll in it, like in the screenshoot linked before. 

![Screenshot 2023-11-10 185249](https://github.com/epinter/tqrespec/assets/150154367/2890efa3-1202-4718-a973-34459bee1f04)


I link you the log file:

[tqrespec log.txt](https://github.com/epinter/tqrespec/files/13322015/tqrespec.log.txt)

**Comment by epinter** [comment]
Same error in log... Let's try one more update:

https://github.com/epinter/tqrespec/releases/tag/dev-20231110-2

**Comment by Redstorm86** [comment]
Same situation :( 

[tqrespec log.txt](https://github.com/epinter/tqrespec/files/13324980/tqrespec.log.txt)

**Comment by epinter** [comment]
I need to think more about it. It's weird, I never saw that problem. Before a release, I always test the build using Windows Sandbox, and it always work. If you don't know, Windows Sandbox is a feature builtin on Windows that you can launch a fresh windows os as an application and test programs like in a vm.

Do you have any clue ? Any software you have installed that could conflict ? For example softwares that apply themes to Windows interface, like Window Blinds...

I can try to upgrade to Java 21 and see if makes a difference, I but don't know if I will need to change code, and I doubt it will make a difference... Anyway, today I will try to simply build with Java 21 and see what happens. If you still want to test, let me know I can post the build here.

**Comment by epinter** [comment]
It was easier than I thought: https://github.com/epinter/tqrespec/releases/tag/dev-20231111

**Comment by Redstorm86** [comment]
Thanks for your effort, i tried all new versions that you linked but all failed with same error log. I tried with my wife's notebook and all works fine, so it's same sort of conflict in my pc, as you said before. I don't want to waste any more of your time, now i will focus to find the cause of this graphic problem, i hope to find it! Thanks again, you are really great! :)

**Comment by epinter** [comment]
If I have any idea, I will reply here. Thank you for your help with all the tests!

**Comment by epinter** [comment]
One last thing ... Try to go to "C:\Windows\Fonts" and "%LOCALAPPDATA%\Microsoft\Windows\Fonts\" and check if you have any invalid or corrupted font installed.

**Comment by Redstorm86** [comment]
I cleaned my Java folder and installed last Java JDK and now all works fine! Probably some old version of Java library was creating something wrong. Thanks for all your tips! :)

**Comment by epinter** [comment]
Good to know! Thanks for feedback!
