### ISSUE TITLE
What does it mean? How do I fix it?

### ISSUE THREAD

**Issue by allomonkey** [epinter/tqrespec#51]
Can't start TQRespec.exe.
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: Exception in Application start method
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: java.lang.reflect.InvocationTargetException
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1082)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: Caused by: java.lang.RuntimeException: Exception in Application start method
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/java.lang.Thread.run(Thread.java:833)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.tqdata.GameInfo.readGameOptions(GameInfo.java:856)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.tqdata.GameInfo.getGameOptionValue(GameInfo.java:834)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.tqdata.GameInfo.getGameLanguage(GameInfo.java:824)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main.prepareMainStage(Main.java:276)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main.start(Main.java:264)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 	... 1 more
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: 
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE: Exception running application br.com.pinter.tqrespec.Main
May 17, 2024 10:40:42 PM br.com.pinter.tqrespec.logging.OutputStreamLog write
SEVERE:

**Comment by epinter** [comment]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at br.com.pinter.tqrespec/br.com.pinter.tqrespec.tqdata.GameInfo.readGameOptions(GameInfo.java:856)
```
An error occured while reading options.txt. See in your options.txt all lines has spaces around equal sign, like:

lockItemPickup            = true
showMonsterLevelOnRollover = true

**Comment by allomonkey** [comment]
Turns out options.txt was altered by Geforce Experience. I deleted options.txt and run the game, make it regenerated one, now TQRespec works perfectly fine.
Thanks a million. You saved the day.
