### ISSUE TITLE
Font with cyrillic support and/or language setting

### ISSUE THREAD

**Issue by gievepix** [epinter/tqrespec#53]
After reinstalling windows I realized that TQRespec now picks language automatically from system settings, so it's russian now (been using english as system language before). Can't say I'm a fan of replacement font it uses for cyrillic symbols:
![image](https://github.com/epinter/tqrespec/assets/35334017/d42a16f0-1da0-43cb-a817-1a3a506c24ac)
Would it be possible to get version of Albertus font with cyrillic support? Or, better, but not mutually exclusive, add an option to change app language in settings?

**Comment by epinter** [comment]
Something happened with the font in recent update, I didn't test Russian... I will see what I can do. The application language is read from game language configuration. If you change your game to English (options.txt, language setting), TQRespec with open in english. Thanks for reporting.

**Comment by gievepix** [comment]
Weird, because I play TQ in english... Even more weird is that language setting in options.txt was empty. Changed language in game settings to russian and then back to english, now it says "English", but TQRespect still runs in russian.

**Comment by epinter** [comment]
I won't publish yet because I need to fix a small issue with window resizing/scaling, but I won't change anything more regarding to the fonts. This build tries to load fonts from game files and use "Albertus MT" font. If the game is not available, fallback fonts are used. For Russian and some other languages, system sans-serif is used.

https://1drv.ms/u/s!AqbcmbBetf3hgw07HIUTn4lFFLQV?e=AgWC4c

**Comment by gievepix** [comment]
Well, I don't know if there was anything done about how application chooses the language, but this build still uses russian with super wide fallback font, disregarding game settings. And only after I changed system language to english, TQRespec finally started using it too.

Hm, I had version of Albertus with cyrillic support, but it's "medium", so numbers are a bit wider than MT, while text is virtually the same. Still, I wonder if it would help to improve readability for russain text?

**Comment by epinter** [comment]
Russian language is not using albertus, and the language is not read from system, it's read from game options.txt. If the game language is not available, then english is used.

![image](https://github.com/epinter/tqrespec/assets/1561280/9ff69c40-0626-42c3-8d12-d3727f570074)

**Comment by gievepix** [comment]
I just did another test on build above, and now when system language is set to english, TQRespec indeed uses language from options.txt, and while russian fallback font isn't exactly the same as on your screenshot, it's very close and indeed readable. Well, I should've checked this before commenting.

So this is something about OS itself (Windows 10, if it matters) and language pack? If setting its language to russian somehow makes TQRespec also use it regardless of game settings, and with wrong fallback font.

And sure, if you come up with something, I can test it.

**Comment by epinter** [comment]
> I just did another test on build above, and now when system language is set to english, TQRespec indeed uses language from options.txt, and while russian fallback font isn't exactly the same as on your screenshot, it's very close and indeed readable. Well, I should've checked this before commenting.
> 
> So this is something about OS itself (Windows 10, if it matters) and language pack? If setting its language to russian somehow makes TQRespec also use it regardless of game settings, and with wrong fallback font.
> 
> And sure, if you come up with something, I can test it.

I think the font chosen by Java VM it's not good for Russian... I will search for a open/free font with support and try to build with it.

**Comment by epinter** [comment]
Try this build. If it still looks weird, send me the tqrespec.log found in your user appdata %TEMP% directory.

https://1drv.ms/u/s!AqbcmbBetf3hgw6lGRh28ULrSR9D?e=0gMnOX

**Comment by gievepix** [comment]
Changed system language back to russian. So, TQRespec finally somehow reacts to change in language setting in options.txt, but only works properly if game language is set to russian (i.e. finally proper font everywhere, no sign of Albertus). With game language set to english UI is still in russian, but tries to use Albertus again, with wide fallback font.

Log for the latter:
[tqrespec.log](https://github.com/user-attachments/files/16042235/tqrespec.log)

**Comment by epinter** [comment]
This is weird. Looking the log there's no sign of Russian language being used (look the "Application language set to 'en'", I show this line when English is detected in options.txt). The Albertus MT font is being selected because the application language is set to english based on options.txt, but somehow the JVM is considering Russian language, it shouldn't because I never use system locale. I will look if there's something that changed in newer JDK, as far as I remember, older versions didn't have this behavior. Thanks very much for you help and patience, I will try to reproduce myself and investigate.

**Comment by epinter** [comment]
I was able to reproduce an fix the problem, this build worked for me:

https://1drv.ms/u/s!AqbcmbBetf3hgw8gQv9sWOlWtNvN?e=uRKyka

**Comment by gievepix** [comment]
I can confirm, this build works for me too.

**Comment by epinter** [comment]
> I can confirm, this build works for me too.

Thank you very much for reporting and helping with testing !! :)
