### ISSUE TITLE
Question about running on diff PCs

### ISSUE THREAD

**Issue by CyberNinja04** [epinter/tqrespec#8]
is there a way to run this on another system and copy the saves over to that one and respec? I tried but it couldnt find the saves and i dont know how to tell it to point to a location, i put it in the same directory tree that it is supposed to be in on the w7 pc on my w10 pc

**Comment by epinter** [comment]
The application needs game installed and the save games in "Documents/My Games/Titan Quest - Immortal Throne".

**Comment by epinter** [comment]
Maybe this helps you: https://github.com/epinter/tqrespec/issues/9
